<?php

namespace Database\Seeders;

class ErpProductsData
{
    public static function getProductsData($unitIds, $productTypeIds, $productGroupIds, $brandIds = [])
    {
        return [
            // Steel Products
            ['name' => 'Steel Rods A36', 'identifier' => 'STEEL001', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['STEEL'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'High-grade steel rods', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Steel Sheets 304', 'identifier' => 'STEEL002', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['STEEL'] ?? null, 'erp_brand_id' => $brandIds['BMW'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'Stainless steel sheets', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Steel Pipes 6 inch', 'identifier' => 'STEEL003', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['STEEL'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Steel pipes for construction', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Steel Beams I-Beam', 'identifier' => 'STEEL004', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['STEEL'] ?? null, 'erp_brand_id' => $brandIds['BMW'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Structural steel beams', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Steel Wire 12 AWG', 'identifier' => 'STEEL005', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['STEEL'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Steel wire for electrical', 'is_active' => true, 'is_locked' => false],
            
            // Aluminum Products
            ['name' => 'Aluminum Sheets 6061', 'identifier' => 'ALUM001', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['ALUM'] ?? null, 'erp_brand_id' => $brandIds['BMW'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'Aerospace grade aluminum', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Aluminum Extrusions', 'identifier' => 'ALUM002', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['ALUM'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Aluminum profile extrusions', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Aluminum Foil', 'identifier' => 'ALUM003', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['ALUM'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'Food grade aluminum foil', 'is_active' => true, 'is_locked' => false],
            
            // Copper Products
            ['name' => 'Copper Wire 14 AWG', 'identifier' => 'COPP001', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['COPP'] ?? null, 'erp_brand_id' => $brandIds['INT'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Electrical copper wire', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Copper Pipes 1/2 inch', 'identifier' => 'COPP002', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['COPP'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Plumbing copper pipes', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Copper Sheets', 'identifier' => 'COPP003', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['COPP'] ?? null, 'erp_brand_id' => $brandIds['BMW'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'Copper sheets for roofing', 'is_active' => true, 'is_locked' => false],
            
            // Electronic Components
            ['name' => 'Resistors 1K Ohm', 'identifier' => 'ELEC001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['ELEC'] ?? null, 'erp_brand_id' => $brandIds['INT'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => '1/4W carbon film resistors', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Capacitors 100uF', 'identifier' => 'ELEC002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['ELEC'] ?? null, 'erp_brand_id' => $brandIds['AMD'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Electrolytic capacitors', 'is_active' => true, 'is_locked' => false],
            ['name' => 'LEDs Red 5mm', 'identifier' => 'ELEC003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['ELEC'] ?? null, 'erp_brand_id' => $brandIds['NVD'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Standard red LEDs', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Arduino Uno', 'identifier' => 'ELEC004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['ELEC'] ?? null, 'erp_brand_id' => $brandIds['APL'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Arduino development board', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Raspberry Pi 4', 'identifier' => 'ELEC005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['ELEC'] ?? null, 'erp_brand_id' => $brandIds['SMS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Single board computer', 'is_active' => true, 'is_locked' => false],
            
            // Hand Tools
            ['name' => 'Screwdriver Set', 'identifier' => 'HAND001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['HAND'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['set'] ?? 1, 'comment' => 'Professional screwdriver set', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Wrench Set', 'identifier' => 'HAND002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['HAND'] ?? null, 'erp_brand_id' => $brandIds['ADS'] ?? null, 'unit_id' => $unitIds['set'] ?? 1, 'comment' => 'Metric wrench set', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Pliers Set', 'identifier' => 'HAND003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['HAND'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['set'] ?? 1, 'comment' => 'Needle nose and regular pliers', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Hammer 16oz', 'identifier' => 'HAND004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['HAND'] ?? null, 'erp_brand_id' => $brandIds['ADS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Claw hammer', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Tape Measure 25ft', 'identifier' => 'HAND005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['HAND'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Retractable tape measure', 'is_active' => true, 'is_locked' => false],
            
            // Power Tools
            ['name' => 'Drill Driver 18V', 'identifier' => 'POWER001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['POWER'] ?? null, 'erp_brand_id' => $brandIds['SMS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Cordless drill driver', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Circular Saw 7.25 inch', 'identifier' => 'POWER002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['POWER'] ?? null, 'erp_brand_id' => $brandIds['LG'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Corded circular saw', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Angle Grinder 4.5 inch', 'identifier' => 'POWER003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['POWER'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Metal cutting grinder', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Jigsaw Variable Speed', 'identifier' => 'POWER004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['POWER'] ?? null, 'erp_brand_id' => $brandIds['SMS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Corded jigsaw', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Impact Wrench 1/2 inch', 'identifier' => 'POWER005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['POWER'] ?? null, 'erp_brand_id' => $brandIds['LG'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Air impact wrench', 'is_active' => true, 'is_locked' => false],
            
            // Office Supplies
            ['name' => 'Ballpoint Pens Blue', 'identifier' => 'OFF001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['OFF'] ?? null, 'erp_brand_id' => $brandIds['MSF'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Blue ink ballpoint pens', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Notebook A4', 'identifier' => 'OFF002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['OFF'] ?? null, 'erp_brand_id' => $brandIds['APL'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Spiral bound notebook', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Stapler Heavy Duty', 'identifier' => 'OFF003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['OFF'] ?? null, 'erp_brand_id' => $brandIds['MSF'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Office stapler', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Paper Clips Large', 'identifier' => 'OFF004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['OFF'] ?? null, 'erp_brand_id' => $brandIds['APL'] ?? null, 'unit_id' => $unitIds['box'] ?? 1, 'comment' => 'Box of paper clips', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Binder 3 Ring', 'identifier' => 'OFF005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['OFF'] ?? null, 'erp_brand_id' => $brandIds['MSF'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => '3-ring binder', 'is_active' => true, 'is_locked' => false],
            
            // Safety Equipment
            ['name' => 'Safety Glasses', 'identifier' => 'SAFE001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['SAFE'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Clear safety glasses', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Hard Hat White', 'identifier' => 'SAFE002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['SAFE'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Construction hard hat', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Work Gloves Leather', 'identifier' => 'SAFE003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['SAFE'] ?? null, 'unit_id' => $unitIds['pair'] ?? 1, 'comment' => 'Leather work gloves', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Safety Vest Orange', 'identifier' => 'SAFE004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['SAFE'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'High visibility safety vest', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Ear Plugs Foam', 'identifier' => 'SAFE005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['SAFE'] ?? null, 'unit_id' => $unitIds['box'] ?? 1, 'comment' => 'Disposable foam ear plugs', 'is_active' => true, 'is_locked' => false],
            
            // Cleaning Supplies
            ['name' => 'All Purpose Cleaner', 'identifier' => 'CLEAN001', 'erp_product_type_id' => $productTypeIds['liquid'] ?? 1, 'erp_product_group_id' => $productGroupIds['CLEAN'] ?? null, 'unit_id' => $unitIds['L'] ?? 1, 'comment' => 'Multi-surface cleaner', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Paper Towels', 'identifier' => 'CLEAN002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['CLEAN'] ?? null, 'unit_id' => $unitIds['box'] ?? 1, 'comment' => 'Industrial paper towels', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Microfiber Cloths', 'identifier' => 'CLEAN003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['CLEAN'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Reusable cleaning cloths', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Floor Cleaner', 'identifier' => 'CLEAN004', 'erp_product_type_id' => $productTypeIds['liquid'] ?? 1, 'erp_product_group_id' => $productGroupIds['CLEAN'] ?? null, 'unit_id' => $unitIds['L'] ?? 1, 'comment' => 'Concentrated floor cleaner', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Trash Bags 30 Gallon', 'identifier' => 'CLEAN005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['CLEAN'] ?? null, 'unit_id' => $unitIds['box'] ?? 1, 'comment' => 'Heavy duty trash bags', 'is_active' => true, 'is_locked' => false],
            
            // Furniture
            ['name' => 'Office Chair Ergonomic', 'identifier' => 'FURN001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['FURN'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Adjustable office chair', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Desk 6ft', 'identifier' => 'FURN002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['FURN'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Wooden office desk', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Filing Cabinet 4 Drawer', 'identifier' => 'FURN003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['FURN'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Metal filing cabinet', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Bookshelf 5 Shelf', 'identifier' => 'FURN004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['FURN'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Wooden bookshelf', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Conference Table 8ft', 'identifier' => 'FURN005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['FURN'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Large conference table', 'is_active' => true, 'is_locked' => false],
            
            // Apparel
            ['name' => 'T-Shirt Cotton M', 'identifier' => 'APP001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['APP'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Cotton t-shirt medium', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Jeans Denim 32x32', 'identifier' => 'APP002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['APP'] ?? null, 'erp_brand_id' => $brandIds['ADS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Blue denim jeans', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Work Boots Steel Toe', 'identifier' => 'APP003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['APP'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['pair'] ?? 1, 'comment' => 'Steel toe work boots', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Hoodie Fleece L', 'identifier' => 'APP004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['APP'] ?? null, 'erp_brand_id' => $brandIds['ADS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Fleece hoodie large', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Baseball Cap', 'identifier' => 'APP005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['APP'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Adjustable baseball cap', 'is_active' => true, 'is_locked' => false],
            
            // Automotive
            ['name' => 'Oil Filter', 'identifier' => 'AUTO001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['AUTO'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Engine oil filter', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Brake Pads Front', 'identifier' => 'AUTO002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['AUTO'] ?? null, 'erp_brand_id' => $brandIds['BMW'] ?? null, 'unit_id' => $unitIds['set'] ?? 1, 'comment' => 'Front brake pad set', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Spark Plugs Iridium', 'identifier' => 'AUTO003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['AUTO'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['set'] ?? 1, 'comment' => 'Iridium spark plug set', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Air Filter', 'identifier' => 'AUTO004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['AUTO'] ?? null, 'erp_brand_id' => $brandIds['BMW'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Engine air filter', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Windshield Wipers', 'identifier' => 'AUTO005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['AUTO'] ?? null, 'erp_brand_id' => $brandIds['TYT'] ?? null, 'unit_id' => $unitIds['set'] ?? 1, 'comment' => 'Windshield wiper blade set', 'is_active' => true, 'is_locked' => false],
            
            // Chemicals
            ['name' => 'Sulfuric Acid 98%', 'identifier' => 'CHEM001', 'erp_product_type_id' => $productTypeIds['liquid'] ?? 1, 'erp_product_group_id' => $productGroupIds['CHEM'] ?? null, 'erp_brand_id' => $brandIds['COC'] ?? null, 'unit_id' => $unitIds['L'] ?? 1, 'comment' => 'Concentrated sulfuric acid', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Sodium Hydroxide', 'identifier' => 'CHEM002', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['CHEM'] ?? null, 'erp_brand_id' => $brandIds['PEP'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'Caustic soda pellets', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Hydrochloric Acid 37%', 'identifier' => 'CHEM003', 'erp_product_type_id' => $productTypeIds['liquid'] ?? 1, 'erp_product_group_id' => $productGroupIds['CHEM'] ?? null, 'erp_brand_id' => $brandIds['COC'] ?? null, 'unit_id' => $unitIds['L'] ?? 1, 'comment' => 'Muriatic acid', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Ethanol 95%', 'identifier' => 'CHEM004', 'erp_product_type_id' => $productTypeIds['liquid'] ?? 1, 'erp_product_group_id' => $productGroupIds['CHEM'] ?? null, 'erp_brand_id' => $brandIds['PEP'] ?? null, 'unit_id' => $unitIds['L'] ?? 1, 'comment' => 'Denatured ethanol', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Acetone', 'identifier' => 'CHEM005', 'erp_product_type_id' => $productTypeIds['liquid'] ?? 1, 'erp_product_group_id' => $productGroupIds['CHEM'] ?? null, 'erp_brand_id' => $brandIds['COC'] ?? null, 'unit_id' => $unitIds['L'] ?? 1, 'comment' => 'Laboratory grade acetone', 'is_active' => true, 'is_locked' => false],
            
            // Textiles
            ['name' => 'Cotton Fabric 100%', 'identifier' => 'TEXT001', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['TEXT'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Pure cotton fabric', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Polyester Thread', 'identifier' => 'TEXT002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['TEXT'] ?? null, 'erp_brand_id' => $brandIds['ADS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Sewing thread', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Denim Fabric', 'identifier' => 'TEXT003', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['TEXT'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Blue denim fabric', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Wool Yarn', 'identifier' => 'TEXT004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['TEXT'] ?? null, 'erp_brand_id' => $brandIds['ADS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Knitting wool yarn', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Canvas Heavy Duty', 'identifier' => 'TEXT005', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['TEXT'] ?? null, 'erp_brand_id' => $brandIds['NKE'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Heavy duty canvas', 'is_active' => true, 'is_locked' => false],
            
            // Plastics
            ['name' => 'PVC Pipe 1 inch', 'identifier' => 'PLAST001', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['PLAST'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Schedule 40 PVC pipe', 'is_active' => true, 'is_locked' => false],
            ['name' => 'ABS Plastic Sheets', 'identifier' => 'PLAST002', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['PLAST'] ?? null, 'erp_brand_id' => $brandIds['LG'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'ABS plastic sheets', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Polyethylene Film', 'identifier' => 'PLAST003', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['PLAST'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Clear polyethylene film', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Nylon Rope 1/4 inch', 'identifier' => 'PLAST004', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['PLAST'] ?? null, 'erp_brand_id' => $brandIds['LG'] ?? null, 'unit_id' => $unitIds['m'] ?? 1, 'comment' => 'Nylon rope', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Acrylic Sheets', 'identifier' => 'PLAST005', 'erp_product_type_id' => $productTypeIds['bulk'] ?? 1, 'erp_product_group_id' => $productGroupIds['PLAST'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['kg'] ?? 1, 'comment' => 'Clear acrylic sheets', 'is_active' => true, 'is_locked' => false],
            
            // Machinery
            ['name' => 'CNC Milling Machine', 'identifier' => 'MACH001', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['MACH'] ?? null, 'erp_brand_id' => $brandIds['SMS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => '3-axis CNC milling machine', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Lathe Machine', 'identifier' => 'MACH002', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['MACH'] ?? null, 'erp_brand_id' => $brandIds['LG'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Engine lathe machine', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Press Brake', 'identifier' => 'MACH003', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['MACH'] ?? null, 'erp_brand_id' => $brandIds['PNS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Hydraulic press brake', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Welding Machine', 'identifier' => 'MACH004', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['MACH'] ?? null, 'erp_brand_id' => $brandIds['SMS'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'MIG welding machine', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Band Saw', 'identifier' => 'MACH005', 'erp_product_type_id' => $productTypeIds['normal'] ?? 1, 'erp_product_group_id' => $productGroupIds['MACH'] ?? null, 'erp_brand_id' => $brandIds['LG'] ?? null, 'unit_id' => $unitIds['pcs'] ?? 1, 'comment' => 'Vertical band saw', 'is_active' => true, 'is_locked' => false],
            
            // Services
            ['name' => 'Consulting Services', 'identifier' => 'SERV001', 'erp_product_type_id' => $productTypeIds['service'] ?? 1, 'erp_product_group_id' => null, 'erp_brand_id' => $brandIds['MSF'] ?? null, 'unit_id' => $unitIds['hr'] ?? 1, 'comment' => 'Professional consulting services', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Maintenance Service', 'identifier' => 'SERV002', 'erp_product_type_id' => $productTypeIds['service'] ?? 1, 'erp_product_group_id' => null, 'erp_brand_id' => $brandIds['APL'] ?? null, 'unit_id' => $unitIds['hr'] ?? 1, 'comment' => 'Equipment maintenance service', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Installation Service', 'identifier' => 'SERV003', 'erp_product_type_id' => $productTypeIds['service'] ?? 1, 'erp_product_group_id' => null, 'erp_brand_id' => $brandIds['MSF'] ?? null, 'unit_id' => $unitIds['hr'] ?? 1, 'comment' => 'Equipment installation service', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Training Service', 'identifier' => 'SERV004', 'erp_product_type_id' => $productTypeIds['service'] ?? 1, 'erp_product_group_id' => null, 'erp_brand_id' => $brandIds['APL'] ?? null, 'unit_id' => $unitIds['hr'] ?? 1, 'comment' => 'Technical training service', 'is_active' => true, 'is_locked' => false],
            ['name' => 'Repair Service', 'identifier' => 'SERV005', 'erp_product_type_id' => $productTypeIds['service'] ?? 1, 'erp_product_group_id' => null, 'erp_brand_id' => $brandIds['MSF'] ?? null, 'unit_id' => $unitIds['hr'] ?? 1, 'comment' => 'Equipment repair service', 'is_active' => true, 'is_locked' => false],
        ];
    }
}
