<?php

namespace Panadero\Erp\Hr\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HrEmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_id' => 'EMP001',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@company.com',
                'phone' => '+1-555-0101',
                'date_of_birth' => '1985-03-15',
                'gender' => 'male',
                'address' => '123 Main Street',
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'USA',
                'emergency_contact_name' => 'Jane Smith',
                'emergency_contact_phone' => '+1-555-0102',
                'emergency_contact_relationship' => 'Spouse',
                'department_id' => 1, // HR
                'position' => 'HR Manager',
                'job_title' => 'Human Resources Manager',
                'employment_type' => 'full_time',
                'hire_date' => '2020-01-15',
                'status' => 'active',
                'salary' => 75000.00,
                'currency' => 'USD',
                'skills' => json_encode(['Recruitment', 'Employee Relations', 'Performance Management', 'HRIS']),
                'certifications' => json_encode(['PHR', 'SHRM-CP']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP002',
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@company.com',
                'phone' => '+1-555-0201',
                'date_of_birth' => '1990-07-22',
                'gender' => 'female',
                'address' => '456 Oak Avenue',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'country' => 'USA',
                'emergency_contact_name' => 'Mike Johnson',
                'emergency_contact_phone' => '+1-555-0202',
                'emergency_contact_relationship' => 'Brother',
                'department_id' => 2, // Engineering
                'position' => 'Senior Developer',
                'job_title' => 'Senior Software Engineer',
                'employment_type' => 'full_time',
                'hire_date' => '2019-06-01',
                'status' => 'active',
                'salary' => 95000.00,
                'currency' => 'USD',
                'skills' => json_encode(['JavaScript', 'Vue.js', 'Node.js', 'Python', 'AWS']),
                'certifications' => json_encode(['AWS Solutions Architect', 'Google Cloud Professional']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP003',
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'email' => 'michael.brown@company.com',
                'phone' => '+1-555-0301',
                'date_of_birth' => '1988-11-08',
                'gender' => 'male',
                'address' => '789 Pine Street',
                'city' => 'Chicago',
                'state' => 'IL',
                'postal_code' => '60601',
                'country' => 'USA',
                'emergency_contact_name' => 'Lisa Brown',
                'emergency_contact_phone' => '+1-555-0302',
                'emergency_contact_relationship' => 'Wife',
                'department_id' => 3, // Marketing
                'position' => 'Marketing Director',
                'job_title' => 'Director of Marketing',
                'employment_type' => 'full_time',
                'hire_date' => '2018-03-10',
                'status' => 'active',
                'salary' => 85000.00,
                'currency' => 'USD',
                'skills' => json_encode(['Digital Marketing', 'SEO', 'Content Strategy', 'Analytics', 'Brand Management']),
                'certifications' => json_encode(['Google Analytics Certified', 'HubSpot Content Marketing']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP004',
                'first_name' => 'Emily',
                'last_name' => 'Davis',
                'email' => 'emily.davis@company.com',
                'phone' => '+1-555-0401',
                'date_of_birth' => '1992-04-12',
                'gender' => 'female',
                'address' => '321 Elm Street',
                'city' => 'Austin',
                'state' => 'TX',
                'postal_code' => '73301',
                'country' => 'USA',
                'emergency_contact_name' => 'Robert Davis',
                'emergency_contact_phone' => '+1-555-0402',
                'emergency_contact_relationship' => 'Father',
                'department_id' => 4, // Sales
                'position' => 'Sales Manager',
                'job_title' => 'Sales Manager',
                'employment_type' => 'full_time',
                'hire_date' => '2021-02-01',
                'status' => 'active',
                'salary' => 70000.00,
                'currency' => 'USD',
                'skills' => json_encode(['Sales Management', 'CRM', 'Lead Generation', 'Customer Relations', 'Negotiation']),
                'certifications' => json_encode(['Salesforce Certified', 'HubSpot Sales']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_id' => 'EMP005',
                'first_name' => 'David',
                'last_name' => 'Wilson',
                'email' => 'david.wilson@company.com',
                'phone' => '+1-555-0501',
                'date_of_birth' => '1983-09-25',
                'gender' => 'male',
                'address' => '654 Maple Drive',
                'city' => 'Seattle',
                'state' => 'WA',
                'postal_code' => '98101',
                'country' => 'USA',
                'emergency_contact_name' => 'Susan Wilson',
                'emergency_contact_phone' => '+1-555-0502',
                'emergency_contact_relationship' => 'Sister',
                'department_id' => 5, // Finance
                'position' => 'CFO',
                'job_title' => 'Chief Financial Officer',
                'employment_type' => 'full_time',
                'hire_date' => '2017-01-15',
                'status' => 'active',
                'salary' => 120000.00,
                'currency' => 'USD',
                'skills' => json_encode(['Financial Planning', 'Budgeting', 'Risk Management', 'Compliance', 'Strategic Planning']),
                'certifications' => json_encode(['CPA', 'CFA']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('hr_employees')->insert($employees);
    }
}
