<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryLocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if data already exists
        if (DB::table('inventory_locations')->count() > 0) {
            $this->command->info('Inventory locations already exist, skipping...');
            return;
        }

        $locations = [
            // Main Warehouse
            [
                'code' => 'WH-MAIN',
                'name' => 'Main Warehouse',
                'description' => 'Primary storage facility for all inventory types',
                'type' => 'warehouse',
                'parent_id' => null,
                'full_path' => 'Main Warehouse',
                'level' => 0,
                'sort_order' => 1,
                'capacity_units' => 10000,
                'capacity_kg' => 50000,
                'capacity_liters' => 20000,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => false,
                'min_temperature' => null,
                'max_temperature' => null,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => true,
                'access_level' => 'restricted',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Zone A - Items Storage
            [
                'code' => 'WH-MAIN-A',
                'name' => 'Zone A - Items Storage',
                'description' => 'Storage area for discrete items and products',
                'type' => 'zone',
                'parent_id' => 1,
                'full_path' => 'Main Warehouse > Zone A',
                'level' => 1,
                'sort_order' => 1,
                'capacity_units' => 5000,
                'capacity_kg' => 10000,
                'capacity_liters' => 0,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => false,
                'min_temperature' => null,
                'max_temperature' => null,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => false,
                'access_level' => 'public',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Zone B - Bulk Materials
            [
                'code' => 'WH-MAIN-B',
                'name' => 'Zone B - Bulk Materials',
                'description' => 'Storage area for bulk materials and raw ingredients',
                'type' => 'zone',
                'parent_id' => 1,
                'full_path' => 'Main Warehouse > Zone B',
                'level' => 1,
                'sort_order' => 2,
                'capacity_units' => 0,
                'capacity_kg' => 30000,
                'capacity_liters' => 0,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => true,
                'min_temperature' => 15.0,
                'max_temperature' => 25.0,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => false,
                'access_level' => 'public',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Zone C - Liquids Storage
            [
                'code' => 'WH-MAIN-C',
                'name' => 'Zone C - Liquids Storage',
                'description' => 'Storage area for liquids and chemicals',
                'type' => 'zone',
                'parent_id' => 1,
                'full_path' => 'Main Warehouse > Zone C',
                'level' => 1,
                'sort_order' => 3,
                'capacity_units' => 0,
                'capacity_kg' => 10000,
                'capacity_liters' => 20000,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => true,
                'min_temperature' => 2.0,
                'max_temperature' => 8.0,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => true,
                'access_level' => 'secure',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Shelves in Zone A
            [
                'code' => 'WH-MAIN-A-S1',
                'name' => 'Shelf A1 - Bread Products',
                'description' => 'Shelf for bread and bakery products',
                'type' => 'shelf',
                'parent_id' => 2,
                'full_path' => 'Main Warehouse > Zone A > Shelf A1',
                'level' => 2,
                'sort_order' => 1,
                'capacity_units' => 500,
                'capacity_kg' => 1000,
                'capacity_liters' => 0,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => false,
                'min_temperature' => null,
                'max_temperature' => null,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => false,
                'access_level' => 'public',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'code' => 'WH-MAIN-A-S2',
                'name' => 'Shelf A2 - Tools & Equipment',
                'description' => 'Shelf for tools and equipment',
                'type' => 'shelf',
                'parent_id' => 2,
                'full_path' => 'Main Warehouse > Zone A > Shelf A2',
                'level' => 2,
                'sort_order' => 2,
                'capacity_units' => 200,
                'capacity_kg' => 500,
                'capacity_liters' => 0,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => false,
                'min_temperature' => null,
                'max_temperature' => null,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => false,
                'access_level' => 'public',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Bins in Shelf A1
            [
                'code' => 'WH-MAIN-A-S1-B1',
                'name' => 'Bin A1-B1 - Premium Bread',
                'description' => 'Bin for premium bread products',
                'type' => 'bin',
                'parent_id' => 5,
                'full_path' => 'Main Warehouse > Zone A > Shelf A1 > Bin A1-B1',
                'level' => 3,
                'sort_order' => 1,
                'capacity_units' => 100,
                'capacity_kg' => 200,
                'capacity_liters' => 0,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => false,
                'min_temperature' => null,
                'max_temperature' => null,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => false,
                'access_level' => 'public',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'code' => 'WH-MAIN-A-S1-B2',
                'name' => 'Bin A1-B2 - Regular Bread',
                'description' => 'Bin for regular bread products',
                'type' => 'bin',
                'parent_id' => 5,
                'full_path' => 'Main Warehouse > Zone A > Shelf A1 > Bin A1-B2',
                'level' => 3,
                'sort_order' => 2,
                'capacity_units' => 150,
                'capacity_kg' => 300,
                'capacity_liters' => 0,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => false,
                'min_temperature' => null,
                'max_temperature' => null,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => false,
                'access_level' => 'public',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Cold Storage for Liquids
            [
                'code' => 'WH-COLD',
                'name' => 'Cold Storage Facility',
                'description' => 'Temperature-controlled storage for perishable liquids',
                'type' => 'warehouse',
                'parent_id' => null,
                'full_path' => 'Cold Storage Facility',
                'level' => 0,
                'sort_order' => 2,
                'capacity_units' => 0,
                'capacity_kg' => 5000,
                'capacity_liters' => 10000,
                'current_units' => 0,
                'current_kg' => 0,
                'current_liters' => 0,
                'temperature_controlled' => true,
                'min_temperature' => 2.0,
                'max_temperature' => 4.0,
                'humidity_controlled' => false,
                'min_humidity' => null,
                'max_humidity' => null,
                'requires_access_card' => true,
                'access_level' => 'secure',
                'is_active' => true,
                'location_properties' => null,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('inventory_locations')->insert($locations);
    }
}