<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryStockLevelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if data already exists
        if (DB::table('inventory_stock_levels')->count() > 0) {
            $this->command->info('Inventory stock levels already exist, skipping...');
            return;
        }

        $stockLevels = [
            [
                'product_id' => 1,
                'warehouse_id' => 1,
                'zone' => 'A1',
                'shelf' => 'A1-S1',
                'bin' => 'A1-S1-B1',
                'current_stock' => 45.0000,
                'reserved_stock' => 5.0000,
                'available_stock' => 40.0000,
                'min_stock_level' => 10.0000,
                'max_stock_level' => 100.0000,
                'reorder_point' => 15.0000,
                'reorder_quantity' => 50.0000,
                'unit_cost' => 3.50,
                'total_value' => 157.50,
                'last_counted' => now()->subDays(2),
                'last_movement' => now()->subHours(3),
                'status' => 'active',
                'notes' => 'Regular stock rotation - good turnover',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'warehouse_id' => 1,
                'zone' => 'B1',
                'shelf' => 'B1-S1',
                'bin' => 'B1-S1-B1',
                'current_stock' => 250.0000,
                'reserved_stock' => 25.0000,
                'available_stock' => 225.0000,
                'min_stock_level' => 50.0000,
                'max_stock_level' => 500.0000,
                'reorder_point' => 75.0000,
                'reorder_quantity' => 200.0000,
                'unit_cost' => 2.25,
                'total_value' => 562.50,
                'last_counted' => now()->subDays(1),
                'last_movement' => now()->subHours(1),
                'status' => 'active',
                'notes' => 'Bulk storage - high usage item',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'warehouse_id' => 1,
                'zone' => 'C1',
                'shelf' => 'C1-S1',
                'bin' => 'C1-S1-B1',
                'current_stock' => 8.0000,
                'reserved_stock' => 0.0000,
                'available_stock' => 8.0000,
                'min_stock_level' => 2.0000,
                'max_stock_level' => 20.0000,
                'reorder_point' => 5.0000,
                'reorder_quantity' => 10.0000,
                'unit_cost' => 45.00,
                'total_value' => 360.00,
                'last_counted' => now()->subDays(5),
                'last_movement' => now()->subDays(1),
                'status' => 'active',
                'notes' => 'Professional equipment - low turnover',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'warehouse_id' => 1,
                'zone' => 'D1',
                'shelf' => 'D1-S1',
                'bin' => 'D1-S1-B1',
                'current_stock' => 12.0000,
                'reserved_stock' => 2.0000,
                'available_stock' => 10.0000,
                'min_stock_level' => 3.0000,
                'max_stock_level' => 25.0000,
                'reorder_point' => 5.0000,
                'reorder_quantity' => 15.0000,
                'unit_cost' => 8.75,
                'total_value' => 105.00,
                'last_counted' => now()->subDays(3),
                'last_movement' => now()->subHours(6),
                'status' => 'active',
                'notes' => 'Premium oil - moderate usage',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'warehouse_id' => 1,
                'zone' => 'E1',
                'shelf' => 'E1-S1',
                'bin' => 'E1-S1-B1',
                'current_stock' => 3.0000,
                'reserved_stock' => 0.0000,
                'available_stock' => 3.0000,
                'min_stock_level' => 1.0000,
                'max_stock_level' => 10.0000,
                'reorder_point' => 2.0000,
                'reorder_quantity' => 5.0000,
                'unit_cost' => 25.00,
                'total_value' => 75.00,
                'last_counted' => now()->subDays(7),
                'last_movement' => now()->subDays(2),
                'status' => 'low_stock',
                'notes' => 'LOW STOCK - Reorder needed soon',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'warehouse_id' => 1,
                'zone' => 'F1',
                'shelf' => 'F1-S1',
                'bin' => 'F1-S1-B1',
                'current_stock' => 15.0000,
                'reserved_stock' => 3.0000,
                'available_stock' => 12.0000,
                'min_stock_level' => 5.0000,
                'max_stock_level' => 30.0000,
                'reorder_point' => 8.0000,
                'reorder_quantity' => 15.0000,
                'unit_cost' => 18.50,
                'total_value' => 277.50,
                'last_counted' => now()->subDays(4),
                'last_movement' => now()->subHours(12),
                'status' => 'active',
                'notes' => 'Essential baking equipment',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'warehouse_id' => 1,
                'zone' => 'G1',
                'shelf' => 'G1-S1',
                'bin' => 'G1-S1-B1',
                'current_stock' => 80.0000,
                'reserved_stock' => 10.0000,
                'available_stock' => 70.0000,
                'min_stock_level' => 20.0000,
                'max_stock_level' => 150.0000,
                'reorder_point' => 30.0000,
                'reorder_quantity' => 50.0000,
                'unit_cost' => 1.25,
                'total_value' => 100.00,
                'last_counted' => now()->subDays(1),
                'last_movement' => now()->subHours(2),
                'status' => 'active',
                'notes' => 'Bulk seasoning - high usage',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'warehouse_id' => 1,
                'zone' => 'H1',
                'shelf' => 'H1-S1',
                'bin' => 'H1-S1-B1',
                'current_stock' => 25.0000,
                'reserved_stock' => 2.0000,
                'available_stock' => 23.0000,
                'min_stock_level' => 5.0000,
                'max_stock_level' => 50.0000,
                'reorder_point' => 10.0000,
                'reorder_quantity' => 20.0000,
                'unit_cost' => 12.00,
                'total_value' => 300.00,
                'last_counted' => now()->subDays(6),
                'last_movement' => now()->subDays(1),
                'status' => 'active',
                'notes' => 'Safety equipment - regular replacement',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('inventory_stock_levels')->insert($stockLevels);
    }
}
