<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryCloseoutsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if data already exists
        if (DB::table('inventory_closeouts')->count() > 0) {
            $this->command->info('Inventory closeouts already exist, skipping...');
            return;
        }

        $closeouts = [
            [
                'period_type' => 'monthly',
                'period_start' => now()->subMonth()->startOfMonth(),
                'period_end' => now()->subMonth()->endOfMonth(),
                'warehouse_id' => 1,
                'status' => 'completed',
                'total_products' => 8,
                'total_value_start' => 1500.00,
                'total_value_end' => 1650.00,
                'total_movements_in' => 1250.00,
                'total_movements_out' => 1100.00,
                'total_adjustments' => 0.00,
                'variance_amount' => 0.00,
                'variance_percentage' => 0.00,
                'notes' => 'Monthly closeout completed successfully',
                'created_by' => 1,
                'approved_by' => 1,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'period_type' => 'weekly',
                'period_start' => now()->subWeek()->startOfWeek(),
                'period_end' => now()->subWeek()->endOfWeek(),
                'warehouse_id' => 1,
                'status' => 'completed',
                'total_products' => 8,
                'total_value_start' => 1650.00,
                'total_value_end' => 1580.00,
                'total_movements_in' => 320.00,
                'total_movements_out' => 390.00,
                'total_adjustments' => 0.00,
                'variance_amount' => 0.00,
                'variance_percentage' => 0.00,
                'notes' => 'Weekly closeout - normal operations',
                'created_by' => 1,
                'approved_by' => 1,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'period_type' => 'monthly',
                'period_start' => now()->subMonths(2)->startOfMonth(),
                'period_end' => now()->subMonths(2)->endOfMonth(),
                'warehouse_id' => 1,
                'status' => 'completed',
                'total_products' => 7,
                'total_value_start' => 1200.00,
                'total_value_end' => 1500.00,
                'total_movements_in' => 800.00,
                'total_movements_out' => 500.00,
                'total_adjustments' => 0.00,
                'variance_amount' => 0.00,
                'variance_percentage' => 0.00,
                'notes' => 'Previous month closeout - inventory growth',
                'created_by' => 1,
                'approved_by' => 1,
                'created_at' => now()->subMonth()->subDays(5),
                'updated_at' => now()->subMonth()->subDays(5),
            ],
        ];

        DB::table('inventory_closeouts')->insert($closeouts);

        // Create closeout items for each closeout
        $closeoutItems = [
            // Monthly closeout items (most recent)
            [
                'closeout_id' => 1,
                'product_id' => 1,
                'stock_start' => 35.0000,
                'stock_end' => 45.0000,
                'movements_in' => 30.0000,
                'movements_out' => 20.0000,
                'adjustments' => 0.0000,
                'value_start' => 122.50,
                'value_end' => 157.50,
                'unit_cost_avg' => 3.50,
                'notes' => 'Good turnover - bread products',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 2,
                'stock_start' => 200.0000,
                'stock_end' => 250.0000,
                'movements_in' => 100.0000,
                'movements_out' => 50.0000,
                'adjustments' => 0.0000,
                'value_start' => 450.00,
                'value_end' => 562.50,
                'unit_cost_avg' => 2.25,
                'notes' => 'Bulk flour - steady consumption',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 3,
                'stock_start' => 10.0000,
                'stock_end' => 8.0000,
                'movements_in' => 0.0000,
                'movements_out' => 2.0000,
                'adjustments' => 0.0000,
                'value_start' => 450.00,
                'value_end' => 360.00,
                'unit_cost_avg' => 45.00,
                'notes' => 'Equipment - low turnover',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 4,
                'stock_start' => 8.0000,
                'stock_end' => 12.0000,
                'movements_in' => 20.0000,
                'movements_out' => 16.0000,
                'adjustments' => 0.0000,
                'value_start' => 70.00,
                'value_end' => 105.00,
                'unit_cost_avg' => 8.75,
                'notes' => 'Oil products - moderate usage',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 5,
                'stock_start' => 5.0000,
                'stock_end' => 3.0000,
                'movements_in' => 0.0000,
                'movements_out' => 2.0000,
                'adjustments' => 0.0000,
                'value_start' => 125.00,
                'value_end' => 75.00,
                'unit_cost_avg' => 25.00,
                'notes' => 'Digital scale - low stock warning',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 6,
                'stock_start' => 12.0000,
                'stock_end' => 15.0000,
                'movements_in' => 8.0000,
                'movements_out' => 5.0000,
                'adjustments' => 0.0000,
                'value_start' => 222.00,
                'value_end' => 277.50,
                'unit_cost_avg' => 18.50,
                'notes' => 'Baking pans - steady demand',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 7,
                'stock_start' => 60.0000,
                'stock_end' => 80.0000,
                'movements_in' => 50.0000,
                'movements_out' => 30.0000,
                'adjustments' => 0.0000,
                'value_start' => 75.00,
                'value_end' => 100.00,
                'unit_cost_avg' => 1.25,
                'notes' => 'Sea salt - bulk seasoning',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'closeout_id' => 1,
                'product_id' => 8,
                'stock_start' => 20.0000,
                'stock_end' => 25.0000,
                'movements_in' => 15.0000,
                'movements_out' => 10.0000,
                'adjustments' => 0.0000,
                'value_start' => 240.00,
                'value_end' => 300.00,
                'unit_cost_avg' => 12.00,
                'notes' => 'Safety equipment - regular replacement',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],

            // Weekly closeout items
            [
                'closeout_id' => 2,
                'product_id' => 1,
                'stock_start' => 45.0000,
                'stock_end' => 40.0000,
                'movements_in' => 10.0000,
                'movements_out' => 15.0000,
                'adjustments' => 0.0000,
                'value_start' => 157.50,
                'value_end' => 140.00,
                'unit_cost_avg' => 3.50,
                'notes' => 'Weekly bread consumption',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'closeout_id' => 2,
                'product_id' => 2,
                'stock_start' => 250.0000,
                'stock_end' => 225.0000,
                'movements_in' => 0.0000,
                'movements_out' => 25.0000,
                'adjustments' => 0.0000,
                'value_start' => 562.50,
                'value_end' => 506.25,
                'unit_cost_avg' => 2.25,
                'notes' => 'Weekly flour usage',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'closeout_id' => 2,
                'product_id' => 4,
                'stock_start' => 12.0000,
                'stock_end' => 10.0000,
                'movements_in' => 0.0000,
                'movements_out' => 2.0000,
                'adjustments' => 0.0000,
                'value_start' => 105.00,
                'value_end' => 87.50,
                'unit_cost_avg' => 8.75,
                'notes' => 'Weekly oil consumption',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'closeout_id' => 2,
                'product_id' => 7,
                'stock_start' => 80.0000,
                'stock_end' => 70.0000,
                'movements_in' => 0.0000,
                'movements_out' => 10.0000,
                'adjustments' => 0.0000,
                'value_start' => 100.00,
                'value_end' => 87.50,
                'unit_cost_avg' => 1.25,
                'notes' => 'Weekly salt usage',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
        ];

        DB::table('inventory_closeout_items')->insert($closeoutItems);
    }
}
