<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryStockMovementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Check if data already exists
        if (DB::table('inventory_stock_movements')->count() > 0) {
            $this->command->info('Inventory stock movements already exist, skipping...');
            return;
        }

        $stockMovements = [
            [
                'stock_item_id' => 1,
                'movement_type' => 'in',
                'quantity' => 100.0000,
                'unit' => 'units',
                'reason' => 'purchase',
                'reference' => 'PO-2025-001',
                'notes' => 'Initial stock from purchase order',
                'from_warehouse_id' => null,
                'to_warehouse_id' => 1,
                'from_zone' => null,
                'to_zone' => 'A1',
                'batch_number' => 'BATCH-001',
                'serial_numbers' => null,
                'expiry_date' => null,
                'unit_cost' => 10.50,
                'total_cost' => 1050.00,
                'created_by' => 1,
                'movement_date' => now()->subDays(5),
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'stock_item_id' => 1,
                'movement_type' => 'out',
                'quantity' => 25.0000,
                'unit' => 'units',
                'reason' => 'sale',
                'reference' => 'SO-2025-001',
                'notes' => 'Sold to customer',
                'from_warehouse_id' => 1,
                'to_warehouse_id' => null,
                'from_zone' => 'A1',
                'to_zone' => null,
                'batch_number' => 'BATCH-001',
                'serial_numbers' => null,
                'expiry_date' => null,
                'unit_cost' => 10.50,
                'total_cost' => 262.50,
                'created_by' => 1,
                'movement_date' => now()->subDays(3),
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'stock_item_id' => 2,
                'movement_type' => 'in',
                'quantity' => 50.0000,
                'unit' => 'kg',
                'reason' => 'purchase',
                'reference' => 'PO-2025-002',
                'notes' => 'Stock replenishment',
                'from_warehouse_id' => null,
                'to_warehouse_id' => 1,
                'from_zone' => null,
                'to_zone' => 'B1',
                'batch_number' => 'BATCH-002',
                'serial_numbers' => null,
                'expiry_date' => now()->addMonths(12),
                'unit_cost' => 5.25,
                'total_cost' => 262.50,
                'created_by' => 1,
                'movement_date' => now()->subDays(4),
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'stock_item_id' => 2,
                'movement_type' => 'out',
                'quantity' => 15.0000,
                'unit' => 'kg',
                'reason' => 'production',
                'reference' => 'PROD-2025-001',
                'notes' => 'Used in production batch',
                'from_warehouse_id' => 1,
                'to_warehouse_id' => null,
                'from_zone' => 'B1',
                'to_zone' => null,
                'batch_number' => 'BATCH-002',
                'serial_numbers' => null,
                'expiry_date' => now()->addMonths(12),
                'unit_cost' => 5.25,
                'total_cost' => 78.75,
                'created_by' => 1,
                'movement_date' => now()->subDays(2),
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'stock_item_id' => 3,
                'movement_type' => 'in',
                'quantity' => 20.0000,
                'unit' => 'units',
                'reason' => 'purchase',
                'reference' => 'PO-2025-004',
                'notes' => 'Tools for maintenance',
                'from_warehouse_id' => null,
                'to_warehouse_id' => 1,
                'from_zone' => null,
                'to_zone' => 'C1',
                'batch_number' => 'BATCH-003',
                'serial_numbers' => json_encode(['SN-001', 'SN-002', 'SN-003']),
                'expiry_date' => null,
                'unit_cost' => 25.00,
                'total_cost' => 500.00,
                'created_by' => 1,
                'movement_date' => now()->subDays(1),
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'stock_item_id' => 4,
                'movement_type' => 'in',
                'quantity' => 200.0000,
                'unit' => 'liters',
                'reason' => 'purchase',
                'reference' => 'PO-2025-002',
                'notes' => 'Raw materials for production',
                'from_warehouse_id' => null,
                'to_warehouse_id' => 1,
                'from_zone' => null,
                'to_zone' => 'D1',
                'batch_number' => 'BATCH-004',
                'serial_numbers' => null,
                'expiry_date' => now()->addMonths(6),
                'unit_cost' => 2.50,
                'total_cost' => 500.00,
                'created_by' => 1,
                'movement_date' => now()->subDays(4),
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'stock_item_id' => 4,
                'movement_type' => 'out',
                'quantity' => 50.0000,
                'unit' => 'liters',
                'reason' => 'production',
                'reference' => 'PROD-2025-002',
                'notes' => 'Used in production batch',
                'from_warehouse_id' => 1,
                'to_warehouse_id' => null,
                'from_zone' => 'D1',
                'to_zone' => null,
                'batch_number' => 'BATCH-004',
                'serial_numbers' => null,
                'expiry_date' => now()->addMonths(6),
                'unit_cost' => 2.50,
                'total_cost' => 125.00,
                'created_by' => 1,
                'movement_date' => now()->subDays(1),
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'stock_item_id' => 5,
                'movement_type' => 'in',
                'quantity' => 30.0000,
                'unit' => 'units',
                'reason' => 'purchase',
                'reference' => 'PO-2025-004',
                'notes' => 'Accessories for tools',
                'from_warehouse_id' => null,
                'to_warehouse_id' => 1,
                'from_zone' => null,
                'to_zone' => 'C2',
                'batch_number' => 'BATCH-005',
                'serial_numbers' => null,
                'expiry_date' => null,
                'unit_cost' => 8.75,
                'total_cost' => 262.50,
                'created_by' => 1,
                'movement_date' => now()->subDays(1),
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'stock_item_id' => 5,
                'movement_type' => 'out',
                'quantity' => 5.0000,
                'unit' => 'units',
                'reason' => 'sale',
                'reference' => 'SO-2025-002',
                'notes' => 'Sold as accessory',
                'from_warehouse_id' => 1,
                'to_warehouse_id' => null,
                'from_zone' => 'C2',
                'to_zone' => null,
                'batch_number' => 'BATCH-005',
                'serial_numbers' => null,
                'expiry_date' => null,
                'unit_cost' => 8.75,
                'total_cost' => 43.75,
                'created_by' => 1,
                'movement_date' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'stock_item_id' => 1,
                'movement_type' => 'adjustment',
                'quantity' => 5.0000,
                'unit' => 'units',
                'reason' => 'adjustment',
                'reference' => 'ADJ-2025-001',
                'notes' => 'Found additional stock during count',
                'from_warehouse_id' => null,
                'to_warehouse_id' => 1,
                'from_zone' => null,
                'to_zone' => 'A1',
                'batch_number' => 'BATCH-001',
                'serial_numbers' => null,
                'expiry_date' => null,
                'unit_cost' => 10.50,
                'total_cost' => 52.50,
                'created_by' => 1,
                'movement_date' => now()->subHours(2),
                'created_at' => now()->subHours(2),
                'updated_at' => now()->subHours(2),
            ]
        ];

        DB::table('inventory_stock_movements')->insert($stockMovements);
    }
}
