<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Page;
use Illuminate\Support\Str;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pages = [
            [
                'id' => 1,
                'title' => 'Bento',
                'file' => 'welcome.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2024-12-08 21:19:46',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 1,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 2,
                'title' => 'Sandbox',
                'file' => 'Sandbox.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 3,
                'title' => 'About',
                'file' => 'About.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'How sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 4,
                'title' => 'Version',
                'file' => 'Version.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Verson: how sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 5,
                'title' => 'Dashboard',
                'file' => 'Dashboard.vue',
                'icon' => 'monitor-dashboard',
                'image' => 'new2.jpg',
                'slogan' => 'Construct the dashboard so you can manage your KPIs',
                'type' => 'dashboard',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 6,
                'title' => 'Dashboard1',
                'file' => 'Dashboard1.vue',
                'icon' => 'monitor-dashboard',
                'image' => 'new2.jpg',
                'slogan' => 'Construct the dashboard so you can manage your KPIs',
                'type' => 'dashboard',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 7,
                'title' => 'Dashboard2',
                'file' => 'Dashboard2.vue',
                'icon' => 'monitor-dashboard',
                'image' => 'new2.jpg',
                'slogan' => 'Construct the dashboard so you can manage your KPIs',
                'type' => 'dashboard',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 8,
                'title' => 'Tiers',
                'file' => 'tiers.vue',
                'icon' => 'monitor-dashboard',
                'image' => 'new2.jpg',
                'slogan' => 'Construct the dashboard so you can manage your KPIs',
                'type' => 'dashboard',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2025-02-15 20:55:25',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 16,
                'title' => 'Config',
                'file' => 'config.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-09 17:52:38',
                'updated_at' => '2025-03-05 14:31:06',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 17,
                'title' => 'Grid',
                'file' => 'grid.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-09 17:53:14',
                'updated_at' => '2025-02-15 20:55:21',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 18,
                'title' => 'content/Posts',
                'file' => 'content/Posts.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-09 20:27:08',
                'updated_at' => '2025-02-23 20:09:15',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 19,
                'title' => 'bots',
                'file' => 'bots.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-10 19:58:15',
                'updated_at' => '2024-12-10 19:58:15',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 20,
                'title' => 'Mood',
                'file' => 'mood.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan',
                'type' => 'content',
                'settings' => '[]',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-01-18 22:42:18',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 1,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 21,
                'title' => 'Resources',
                'file' => 'resources.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-10 19:58:15',
                'updated_at' => '2025-03-05 14:02:01',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 22,
                'title' => 'Web3',
                'file' => 'web3.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-10 19:58:15',
                'updated_at' => '2025-03-05 14:10:27',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 23,
                'title' => 'Table',
                'file' => 'table.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-10 19:58:15',
                'updated_at' => '2025-03-05 14:10:27',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 24,
                'title' => 'Project',
                'file' => 'project.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'new2.jpg',
                'slogan' => 'Manual: Sandbox sustainability focus accelerates innovation at the heart of your businesss',
                'type' => 'content',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-10 19:58:15',
                'updated_at' => '2025-03-05 14:02:01',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 25,
                'title' => 'home/dashboard',
                'file' => 'Dashboard.vue',
                'icon' => 'monitor-dashboard',
                'image' => 'new2.jpg',
                'slogan' => 'Construct the dashboard so you can manage your KPIs',
                'type' => 'dashboard',
                'settings' => '{}',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-08 21:36:35',
                'updated_at' => '2024-12-08 21:36:35',
                'is_active' => 1,
                'sidebar' => 0,
                'header' => 0,
                'footer' => 0,
                'public' => 0,
                'animate' => 0,
                'max_width' => 0,
            ],
            [
                'id' => 26,
                'title' => 'project/Work',
                'file' => 'work.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan',
                'type' => 'content',
                'settings' => '[]',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-01-18 22:42:18',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 1,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 27,
                'title' => 'home/Welkom',
                'file' => 'welkom.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan1234',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],

            [
                'id' => 28,
                'title' => 'home/Administration',
                'file' => 'administration.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan1234',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 29,
                'title' => 'home/Futures',
                'file' => 'home/futures.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan1234',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 30,
                'title' => 'project/Projects',
                'file' => 'project/projects.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan1234',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 31,
                'title' => 'home/Businessservices', // <-- this shoud match the actual file
                'file' => 'home/Businessservices.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan1234',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 32,
                'title' => 'admin/Middleware', // <-- this shoud match the actual file
                'file' => 'admin/Middleware.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Home Slogan1234',
                'type' => 'Home',
                'settings' => 'Home',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 33,
                'title' => 'admin/Permissions', // <-- this shoud match the actual file
                'file' => 'admin/Permissions.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Admin Slogan1234',
                'type' => 'Admin',
                'settings' => 'Admin',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 34,
                'title' => 'admin/Roles', // <-- this shoud match the actual file
                'file' => 'admin/Role.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Default Admin Slogan1234',
                'type' => 'Admin',
                'settings' => 'Admin',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
            [
                'id' => 35,
                'title' => 'indigo1/Orders',
                'file' => 'indigo1/Orders.vue',
                'icon' => 'view-dashboard-outline',
                'image' => 'h-80 text-4xl text-black bg-contain bg-[url(../images/new2.jpg)]',
                'slogan' => 'Indigo1 Orders Management',
                'type' => 'Indigo1',
                'settings' => 'Indigo1',
                'user_id' => 1,
                'project_id' => 1,
                'created_at' => '2024-12-07 22:31:41',
                'updated_at' => '2025-05-20 21:31:48',
                'is_active' => 1,
                'sidebar' => 1,
                'header' => 1,
                'footer' => 0,
                'public' => 1,
                'animate' => 1,
                'max_width' => 1,
            ],
        ];

        foreach ($pages as $data) {
            Page::updateOrCreate(['id' => $data['id']], $data);
        }
    }
}
