<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'id' => 1,
                'name' => 'Kobe Lueilwitz',
                'email' => 'myrtis.kunde@example.org',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'ULN4572WhI',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 2,
                'name' => 'Mr. Tre Hettinger',
                'email' => 'mandy78@example.net',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => '1n5JmtxdMh',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 3,
                'name' => 'Kristy Kuhlman',
                'email' => 'rconnelly@example.org',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'niA1kYzxVU',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 4,
                'name' => 'Brock Cole',
                'email' => 'kessler.summer@example.org',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'Cx5ZQOSURW',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 5,
                'name' => 'Prof. Amalia Nienow V',
                'email' => 'noreilly@example.net',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'mfZYDPzsUh',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 6,
                'name' => 'Lenora Fritsch',
                'email' => 'maiya57@example.net',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'l1mDriKqpk',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 7,
                'name' => 'Edythe Hermann',
                'email' => 'davis.jillian@example.org',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'Li2WnCs3pD',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 8,
                'name' => 'Cora Kirlin',
                'email' => 'tferry@example.com',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'qEzEJaksKf',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 9,
                'name' => 'Jimmy Frami I',
                'email' => 'rolfson.wallace@example.com',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'MTBciqr4e1',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/SO2RwDxShsxGQrcyvZg3OqRSYQdwPAcOomWpbKie.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 10,
                'name' => 'Kaden Ondricka',
                'email' => 'cleora.senger@example.org',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$qMp7gVzs.9Y/TWbdeYx7teHesPEBrpkkieg.nTiff7BGx1Ac/iYDe',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'B8t4Zyk4WX',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/3pYUIZLgRxFY4lVx17yvhtVq3i3hm5os711Nd9Rc.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2024-10-02 15:39:41',
                'json' => '{}',
            ],
            [
                'id' => 11,
                'name' => 'Luis Panadero',
                'email' => 'lbakker@me.com',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$491HFUECghSM2SKYrAxQ9O5obnz82AD0.84LIBUGVR2Bynj4SHrTy',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'sZZ1SqFh6DgSfxeo5KFFlElho7iDAJ5xerrniLqOdWBOmDxnOh5sBkT9042n',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/8KQH15ZhPoInuIRufLtdthz84p2cmeL4CtB6mm7K.png',
                'created_at' => '2024-10-02 15:39:41',
                'updated_at' => '2025-06-03 02:15:21',
                'json' => '{}',
            ],
            [
                'id' => 12,
                'name' => 'JaWsome Orbit',
                'email' => 'jawsome.orbit@gmail.com',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$491HFUECghSM2SKYrAxQ9O5obnz82AD0.84LIBUGVR2Bynj4SHrTy',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'gbuXKzPJSvhHpu7YL9eu0zW7gwu0W2HbPEdK1yVY9SA6d0XjlLSPdFpqdN1B',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/ge8nmhKA6h6oz02Ifr7M0JAzIL25ZUqCaPOkUUW6.png',
                'created_at' => '2024-10-02 18:52:47',
                'updated_at' => '2024-10-02 18:53:07',
                'json' => '{}',
            ],
            [
                'id' => 13,
                'name' => 'Eric Scott',
                'email' => 'eric.scott@selfcrypto.io',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$491HFUECghSM2SKYrAxQ9O5obnz82AD0.84LIBUGVR2Bynj4SHrTy',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'UlQnYuF7s7SBSt4TW94jzDZOzdSoCdeBTG10I1ICsTPHGrwqG4w6odDNjsll',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/ge8nmhKA6h6oz02Ifr7M0JAzIL25ZUqCaPOkUUW6.png',
                'created_at' => '2024-10-02 18:52:47',
                'updated_at' => '2024-10-02 18:52:47',
                'json' => '{}',
            ],
            [
                'id' => 14,
                'name' => 'Rico Ferrater',
                'email' => 'enrique.ferrater@selfcrypto.io',
                'email_verified_at' => '2024-10-02 15:39:41',
                'role_id' => 1,
                'password' => '$2y$12$491HFUECghSM2SKYrAxQ9O5obnz82AD0.84LIBUGVR2Bynj4SHrTy',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'WnaCLiZDrlI9hpUqk0Iippr9NSE7hOXXsyLuanda9Te1kaaPOmSDkKvSJxJJ',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/ge8nmhKA6h6oz02Ifr7M0JAzIL25ZUqCaPOkUUW6.png',
                'created_at' => '2024-10-02 18:52:47',
                'updated_at' => '2024-10-02 18:52:47',
                'json' => '{}',
            ],
            [
                'id' => 15,
                'name' => 'Vince Bakker',
                'email' => 'vincepbakker@gmail.com',
                'email_verified_at' => '2024-10-02 16:00:00',
                'role_id' => 1,
                'password' => '$2y$12$491HFUECghSM2SKYrAxQ9O5obnz82AD0.84LIBUGVR2Bynj4SHrTy',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/ge8nmhKA6h6oz02Ifr7M0JAzIL25ZUqCaPOkUUW6.png',
                'created_at' => '2024-10-02 18:52:47',
                'updated_at' => '2024-10-02 18:52:47',
                'json' => '{}',
            ],
            [
                'id' => 16,
                'name' => 'Rufi',
                'email' => 'ruwaifatahirr@gmail.com',
                'email_verified_at' => '2024-10-02 16:00:00',
                'role_id' => 1,
                'password' => '$2y$12$491HFUECghSM2SKYrAxQ9O5obnz82AD0.84LIBUGVR2Bynj4SHrTy',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'GFeoTNoQyPk2XXywHbznYTDex7p2ug960CCn4xezQyOZhSsKRINvmAFijxJn',
                'current_team_id' => 1,
                'profile_photo_path' => 'profile-photos/ge8nmhKA6h6oz02Ifr7M0JAzIL25ZUqCaPOkUUW6.png',
                'created_at' => '2024-10-02 18:52:47',
                'updated_at' => '2024-10-02 18:52:47',
                'json' => '{}',
            ],
        ];

        foreach ($users as $user) {
            \App\Models\User::updateOrCreate(['id' => $user['id']], $user);
        }
    }
}
