<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventoryItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // Electronics Category
            [
                'sku' => 'ELC-001',
                'name' => 'Arduino Uno R3',
                'category' => 'Electronics',
                'description' => 'Microcontroller board for prototyping and DIY projects',
                'current_stock' => 45,
                'min_stock' => 20,
                'max_stock' => 100,
                'unit_cost' => 18.50,
                'unit_price' => 29.99,
                'location' => 'Warehouse A - Electronics Section - Shelf E1',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ELC-002',
                'name' => 'Raspberry Pi 4 Model B',
                'category' => 'Electronics',
                'description' => 'Single-board computer with 4GB RAM',
                'current_stock' => 23,
                'min_stock' => 10,
                'max_stock' => 50,
                'unit_cost' => 45.00,
                'unit_price' => 75.00,
                'location' => 'Warehouse A - Electronics Section - Shelf E2',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ELC-003',
                'name' => 'ESP32 Development Board',
                'category' => 'Electronics',
                'description' => 'WiFi and Bluetooth enabled microcontroller',
                'current_stock' => 67,
                'min_stock' => 30,
                'max_stock' => 150,
                'unit_cost' => 8.99,
                'unit_price' => 15.99,
                'location' => 'Warehouse A - Electronics Section - Shelf E3',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ELC-004',
                'name' => 'LED Strip 5m RGB',
                'category' => 'Electronics',
                'description' => 'Addressable RGB LED strip with 300 LEDs',
                'current_stock' => 12,
                'min_stock' => 5,
                'max_stock' => 25,
                'unit_cost' => 25.00,
                'unit_price' => 39.99,
                'location' => 'Warehouse A - Electronics Section - Shelf E4',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ELC-005',
                'name' => 'Breadboard 830 Points',
                'category' => 'Electronics',
                'description' => 'Solderless breadboard for prototyping',
                'current_stock' => 89,
                'min_stock' => 40,
                'max_stock' => 200,
                'unit_cost' => 3.50,
                'unit_price' => 6.99,
                'location' => 'Warehouse A - Electronics Section - Shelf E5',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hardware Category
            [
                'sku' => 'HWD-001',
                'name' => 'M3 Hex Bolts 20mm',
                'category' => 'Hardware',
                'description' => 'Stainless steel hex bolts, M3 x 20mm, pack of 100',
                'current_stock' => 15,
                'min_stock' => 5,
                'max_stock' => 30,
                'unit_cost' => 12.99,
                'unit_price' => 19.99,
                'location' => 'Warehouse B - Hardware Section - Shelf H1',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'HWD-002',
                'name' => 'M4 Nuts Zinc Plated',
                'category' => 'Hardware',
                'description' => 'Zinc plated M4 nuts, pack of 200',
                'current_stock' => 8,
                'min_stock' => 3,
                'max_stock' => 20,
                'unit_cost' => 8.50,
                'unit_price' => 14.99,
                'location' => 'Warehouse B - Hardware Section - Shelf H2',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'HWD-003',
                'name' => 'Washers M4 Flat',
                'category' => 'Hardware',
                'description' => 'Flat washers M4, stainless steel, pack of 500',
                'current_stock' => 22,
                'min_stock' => 10,
                'max_stock' => 50,
                'unit_cost' => 15.00,
                'unit_price' => 24.99,
                'location' => 'Warehouse B - Hardware Section - Shelf H3',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'HWD-004',
                'name' => 'Aluminum Profile 2020',
                'category' => 'Hardware',
                'description' => '20x20mm aluminum extrusion, 1 meter length',
                'current_stock' => 35,
                'min_stock' => 15,
                'max_stock' => 80,
                'unit_cost' => 8.99,
                'unit_price' => 14.99,
                'location' => 'Warehouse B - Hardware Section - Shelf H4',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'HWD-005',
                'name' => 'T-Slot Nuts M4',
                'category' => 'Hardware',
                'description' => 'T-slot nuts for 2020 aluminum profile, M4 thread',
                'current_stock' => 156,
                'min_stock' => 50,
                'max_stock' => 300,
                'unit_cost' => 0.45,
                'unit_price' => 0.89,
                'location' => 'Warehouse B - Hardware Section - Shelf H5',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tools Category
            [
                'sku' => 'TOL-001',
                'name' => 'Digital Multimeter',
                'category' => 'Tools',
                'description' => 'Professional digital multimeter with auto-ranging',
                'current_stock' => 7,
                'min_stock' => 3,
                'max_stock' => 15,
                'unit_cost' => 45.00,
                'unit_price' => 79.99,
                'location' => 'Warehouse C - Tools Section - Shelf T1',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'TOL-002',
                'name' => 'Soldering Iron 60W',
                'category' => 'Tools',
                'description' => 'Temperature controlled soldering iron with stand',
                'current_stock' => 4,
                'min_stock' => 2,
                'max_stock' => 10,
                'unit_cost' => 35.00,
                'unit_price' => 59.99,
                'location' => 'Warehouse C - Tools Section - Shelf T2',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'TOL-003',
                'name' => 'Wire Strippers',
                'category' => 'Tools',
                'description' => 'Professional wire strippers for various wire gauges',
                'current_stock' => 12,
                'min_stock' => 5,
                'max_stock' => 25,
                'unit_cost' => 18.50,
                'unit_price' => 29.99,
                'location' => 'Warehouse C - Tools Section - Shelf T3',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'TOL-004',
                'name' => 'Precision Screwdriver Set',
                'category' => 'Tools',
                'description' => '32-piece precision screwdriver set with case',
                'current_stock' => 9,
                'min_stock' => 4,
                'max_stock' => 20,
                'unit_cost' => 22.00,
                'unit_price' => 39.99,
                'location' => 'Warehouse C - Tools Section - Shelf T4',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'TOL-005',
                'name' => 'Heat Gun 2000W',
                'category' => 'Tools',
                'description' => 'Professional heat gun with variable temperature control',
                'current_stock' => 3,
                'min_stock' => 1,
                'max_stock' => 8,
                'unit_cost' => 55.00,
                'unit_price' => 89.99,
                'location' => 'Warehouse C - Tools Section - Shelf T5',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Raw Materials Category
            [
                'sku' => 'RWM-001',
                'name' => 'Copper Wire 18 AWG',
                'category' => 'Raw Materials',
                'description' => 'Solid copper wire, 18 AWG, 100 feet spool',
                'current_stock' => 24,
                'min_stock' => 10,
                'max_stock' => 50,
                'unit_cost' => 12.99,
                'unit_price' => 19.99,
                'location' => 'Warehouse D - Raw Materials - Shelf R1',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'RWM-002',
                'name' => 'PCB Board 10x15cm',
                'category' => 'Raw Materials',
                'description' => 'FR4 PCB board, 10x15cm, double-sided',
                'current_stock' => 67,
                'min_stock' => 30,
                'max_stock' => 150,
                'unit_cost' => 2.50,
                'unit_price' => 4.99,
                'location' => 'Warehouse D - Raw Materials - Shelf R2',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'RWM-003',
                'name' => 'Solder Wire 0.8mm',
                'category' => 'Raw Materials',
                'description' => 'Lead-free solder wire, 0.8mm diameter, 100g spool',
                'current_stock' => 18,
                'min_stock' => 8,
                'max_stock' => 40,
                'unit_cost' => 8.99,
                'unit_price' => 14.99,
                'location' => 'Warehouse D - Raw Materials - Shelf R3',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'RWM-004',
                'name' => 'Heat Shrink Tubing Set',
                'category' => 'Raw Materials',
                'description' => 'Assorted heat shrink tubing, 3mm to 25mm',
                'current_stock' => 31,
                'min_stock' => 15,
                'max_stock' => 60,
                'unit_cost' => 15.00,
                'unit_price' => 24.99,
                'location' => 'Warehouse D - Raw Materials - Shelf R4',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'RWM-005',
                'name' => 'Jumper Wires Male-Female',
                'category' => 'Raw Materials',
                'description' => '40-piece jumper wire set, male-female connectors',
                'current_stock' => 45,
                'min_stock' => 20,
                'max_stock' => 100,
                'unit_cost' => 4.99,
                'unit_price' => 8.99,
                'location' => 'Warehouse D - Raw Materials - Shelf R5',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Accessories Category
            [
                'sku' => 'ACC-001',
                'name' => 'USB Cable Type-C',
                'category' => 'Accessories',
                'description' => 'USB-C to USB-A cable, 1 meter, data transfer',
                'current_stock' => 78,
                'min_stock' => 30,
                'max_stock' => 150,
                'unit_cost' => 3.99,
                'unit_price' => 6.99,
                'location' => 'Warehouse E - Accessories - Shelf A1',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ACC-002',
                'name' => 'MicroSD Card 32GB',
                'category' => 'Accessories',
                'description' => 'Class 10 MicroSD card, 32GB capacity',
                'current_stock' => 23,
                'min_stock' => 10,
                'max_stock' => 50,
                'unit_cost' => 8.99,
                'unit_price' => 14.99,
                'location' => 'Warehouse E - Accessories - Shelf A2',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ACC-003',
                'name' => 'Power Supply 5V 3A',
                'category' => 'Accessories',
                'description' => 'Switching power supply, 5V 3A with barrel connector',
                'current_stock' => 15,
                'min_stock' => 6,
                'max_stock' => 30,
                'unit_cost' => 12.99,
                'unit_price' => 19.99,
                'location' => 'Warehouse E - Accessories - Shelf A3',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ACC-004',
                'name' => 'Cooling Fan 40mm',
                'category' => 'Accessories',
                'description' => '40mm cooling fan, 12V DC, ball bearing',
                'current_stock' => 42,
                'min_stock' => 20,
                'max_stock' => 80,
                'unit_cost' => 4.50,
                'unit_price' => 7.99,
                'location' => 'Warehouse E - Accessories - Shelf A4',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'ACC-005',
                'name' => 'Project Box 100x60x25mm',
                'category' => 'Accessories',
                'description' => 'Plastic project enclosure with mounting holes',
                'current_stock' => 28,
                'min_stock' => 12,
                'max_stock' => 60,
                'unit_cost' => 6.99,
                'unit_price' => 11.99,
                'location' => 'Warehouse E - Accessories - Shelf A5',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Low Stock Items (for testing alerts)
            [
                'sku' => 'LOW-001',
                'name' => 'Rare Component X',
                'category' => 'Electronics',
                'description' => 'Specialized component with limited availability',
                'current_stock' => 2,
                'min_stock' => 5,
                'max_stock' => 20,
                'unit_cost' => 125.00,
                'unit_price' => 199.99,
                'location' => 'Warehouse A - Electronics Section - Shelf E6',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'LOW-002',
                'name' => 'Specialized Tool Y',
                'category' => 'Tools',
                'description' => 'Professional tool with long lead time',
                'current_stock' => 1,
                'min_stock' => 3,
                'max_stock' => 10,
                'unit_cost' => 89.99,
                'unit_price' => 149.99,
                'location' => 'Warehouse C - Tools Section - Shelf T6',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Discontinued Items
            [
                'sku' => 'DIS-001',
                'name' => 'Legacy Controller V1',
                'category' => 'Electronics',
                'description' => 'Old version controller being phased out',
                'current_stock' => 8,
                'min_stock' => 0,
                'max_stock' => 0,
                'unit_cost' => 15.00,
                'unit_price' => 25.00,
                'location' => 'Warehouse A - Clearance Section',
                'status' => 'discontinued',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'DIS-002',
                'name' => 'Obsolete Sensor Z',
                'category' => 'Electronics',
                'description' => 'Sensor no longer manufactured, clearance sale',
                'current_stock' => 12,
                'min_stock' => 0,
                'max_stock' => 0,
                'unit_cost' => 8.00,
                'unit_price' => 12.00,
                'location' => 'Warehouse A - Clearance Section',
                'status' => 'discontinued',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // High-Value Items
            [
                'sku' => 'HIG-001',
                'name' => 'Industrial PLC Module',
                'category' => 'Electronics',
                'description' => 'Programmable Logic Controller module for automation',
                'current_stock' => 3,
                'min_stock' => 1,
                'max_stock' => 8,
                'unit_cost' => 450.00,
                'unit_price' => 699.99,
                'location' => 'Warehouse A - High Value Section - Vault',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'HIG-002',
                'name' => 'Precision Oscilloscope',
                'category' => 'Tools',
                'description' => 'Digital oscilloscope, 100MHz bandwidth',
                'current_stock' => 1,
                'min_stock' => 1,
                'max_stock' => 3,
                'unit_cost' => 1200.00,
                'unit_price' => 1899.99,
                'location' => 'Warehouse C - High Value Section - Vault',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('inventory_items')->insert($items);
    }
}