// ERP Finance Module Pricing Plans
export default [
  {
    title: 'Basic',
    price: '$49',
    priceRange: '$49-$79',
    period: 'per user/month',
    description: 'Core ERP features for startups and small businesses',
    features: [
      'Core ERP features (inventory, basic finances)',
      'Light AI capabilities (simple alerts)',
      '5-20 users included',
      'Basic support',
      'Standard integrations',
      'Monthly billing',
      { text: 'Base setup fee: $500', tooltip: 'One-time setup and configuration fee.' },
    ],
    popular: false,
    cta: {
      label: 'Start Basic Plan',
      href: '#contact-form',
    },
    setupFee: '$500',
    minUsers: 5,
    maxUsers: 20,
  },
  {
    title: 'Pro',
    price: '$99',
    priceRange: '$99-$129',
    period: 'per user/month',
    description: 'Advanced features with full customization and AI',
    features: [
      'Everything in Basic',
      'Full customization options',
      'Advanced AI (predictive forecasting)',
      'Resource optimization',
      '20-100 users included',
      'Priority support',
      'Advanced integrations',
      'API access',
      { text: 'Base setup fee: $1,000', tooltip: 'One-time setup with advanced configuration.' },
    ],
    popular: true,
    cta: {
      label: 'Start Pro Plan',
      href: '#contact-form',
    },
    setupFee: '$1,000',
    minUsers: 20,
    maxUsers: 100,
  },
  {
    title: 'Enterprise',
    price: '$149',
    priceRange: '$149-$199',
    period: 'per user/month',
    description: 'Unlimited custom AI modules and enterprise features',
    features: [
      'Everything in Pro',
      'Unlimited custom AI modules',
      'Advanced integrations',
      'Priority support (1-hour response)',
      'Dedicated account manager',
      'Custom development',
      'White-label options',
      'Advanced security features',
      { text: 'Base setup fee: $2,000', tooltip: 'One-time setup with full enterprise configuration.' },
    ],
    popular: false,
    cta: {
      label: 'Contact Sales',
      href: '#contact-form',
    },
    setupFee: '$2,000',
    minUsers: 100,
    maxUsers: 'Unlimited',
  },
];
